---
- name: Test IOS Facts
  hosts: all
  tasks:
    - debug:
        var: ansible_facts

    - name: Gather IOS Facts All
      ios_facts:
        gather_subset: all
      register: all_subset

    - name: Print Subset All
      debug:
        var: all_subset


    - name: Gather IOS Facts HW
      ios_facts:
        gather_subset: hardware
      register: hw

    - name: Print Subset HW
      debug:
        var: hw


    - name: Gather IOS Facts Interface
      ios_facts:
        gather_subset: interfaces
      register: int

    - name: Print Subset Interface
      debug:
        var: int


