---
- name: Cisco IOS Command Demo
  hosts: all

  tasks:

    - name: Execute show command
      ios_command:
        commands:
          - show run
          - show ip int brief
      register: sh_outputs
    - debug:
        msg: "{{sh_outputs.stdout_lines}}"

    - name: Check Conditions
      ios_command:
        commands:
          - show run
          - show ip int brief
        match: any
        wait_for:
          - result[0] contains GigabitEthernet1
          - result[1] contains GigabitEthernet1
