---
- name: Update DNS and NTP settings on Cisco switches
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: ios
    ansible_user: "brandonbogle"
    ansible_ssh_pass: "Lab2023!"
    ansible_become_pass: "your_enable_password"
    new_dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
    new_ntp_servers:
      - "0.pool.ntp.org"
      - "1.pool.ntp.org"

  tasks:
    - name: Gather existing DNS server configurations
      ios_command:
        commands: "show running-config | include ip name-server"
      register: dns_output

    - name: Parse existing DNS server IPs
      set_fact:
        old_dns_servers: "{{ dns_output.stdout_lines | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

    - name: Debug old_dns_servers
      debug:
        var: old_dns_servers

    - name: Remove old DNS servers
      ios_config:
        lines:
          - "no ip name-server {{ item }}"
      loop: "{{ old_dns_servers }}"
      when: old_dns_servers is defined and old_dns_servers | length > 0

    - name: Set new DNS servers
      ios_config:
        lines:
          - "ip name-server {{ new_dns_servers | join(' ') }}"

    - name: Gather existing NTP server configurations
      ios_command:
        commands: "show running-config | include ntp server"
      register: ntp_output

    - name: Parse existing NTP server IPs
      set_fact:
        old_ntp_servers: "{{ ntp_output.stdout_lines | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

    - name: Remove old NTP servers one by one
      ios_config:
        lines:
          - "no ntp server {{ item }}"
      loop: "{{ old_ntp_servers }}"
      when: old_ntp_servers is defined and old_ntp_servers | length > 0
      loop_control:
       pause: 2

    - name: Set new NTP servers
      ios_config:
        lines:
          - "ntp server {{ item }}"
      loop: "{{ new_ntp_servers }}"

