all:
  children:
    cisco_routers:
      hosts:
        CSR1:
          ansible_host: 192.168.109.129
          ansible_user: ansible_admin
        CSR2:
          ansible_host: 192.168.109.131
        CSR3:
          ansible_host: 192.168.109.130
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: brandonbogle
        ansible_password: NewPassword1
        ansible_become: yes
        ansible_become_method: enable



