---
- name: Manage NTP Configuration on Cisco Devices
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: ios
    ansible_user: "brandonbogle"
    ansible_ssh_pass: "NewPassword1"
    ansible_become_pass: "your_enable_password"  # Replace with your enable password

  tasks:
    - name: Override NTP configurations
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: "0.pool.ntp.org"
              prefer: true
              use_ipv4: true
            - peer: "1.pool.ntp.org"
              use_ipv4: true
        state: overridden
