---
- name: Manage NTP Configuration on Cisco Devices
  hosts: cisco_routers
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Override NTP configurations
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: "0.pool.ntp.org"
              prefer: true
              use_ipv4: true
            - peer: "1.pool.ntp.org"
              use_ipv4: true
        state: overridden
